// [LAW:single-enforcer] One tokenizer instance for the entire app.
// [LAW:dataflow-not-control-flow] Per-kind correction dispatches on the `kind`
// tag in the input, not branches scattered across callers. The adapter emits
// BillableChunk[]; this module sums them using per-kind factors loaded from
// tokenizer-corrections.json (regenerated by scripts/analyze-calibration.ts).
import { encoding_for_model } from "tiktoken";
import type { BillableChunk, ContentKind } from "../../shared/types";
import corrections from "./tokenizer-corrections.json";

// cl200k_base (gpt-4o) is OpenAI's BPE; it's the wrong vocab for Claude.
// We use it as a *raw length signal* and apply per-kind correction constants
// learned by calling Anthropic's count_tokens endpoint offline during
// calibration. See docs/tokenizer-calibration.md for the methodology.
const enc = encoding_for_model("gpt-4o");

interface KindCorrection {
  a: number; // slope
  b: number; // intercept
  sampleCount: number;
  r2: number;
  rmse: number;
}

interface CorrectionsFile {
  __comment?: string;
  generatedAt: string;
  corpusHashes: string[];
  kinds: Record<ContentKind, KindCorrection>;
}

const TABLE = corrections as CorrectionsFile;

/** Raw tiktoken token count — no Claude-specific correction. */
export function countRawTiktoken(text: string): number {
  return enc.encode(text).length;
}

/** Apply the per-kind correction learned from calibration. */
export function correctTiktoken(raw: number, kind: ContentKind): number {
  const c = TABLE.kinds[kind];
  if (!c) return raw;
  return Math.max(0, Math.round(c.a * raw + c.b));
}

/** Count tokens for a single string tagged by content kind. */
export function countTokensByKind(text: string, kind: ContentKind): number {
  return correctTiktoken(countRawTiktoken(text), kind);
}

/** Sum corrected token counts over a tagged-chunk array. */
export function sumChunks(chunks: BillableChunk[]): number {
  let total = 0;
  for (const chunk of chunks) total += countTokensByKind(chunk.text, chunk.kind);
  return total;
}

/**
 * Back-compat for callers that don't have a ContentKind handy yet.
 * Treats the text as `assistant_text` — the most common kind. Prefer
 * countTokensByKind / sumChunks for new code.
 */
export function countTokens(text: string): number {
  return countTokensByKind(text, "assistant_text");
}

/** Keep the first and last `keep` tokens, replace the middle with ellipsis. */
export function truncateMiddle(text: string, keep = 100): string {
  const tokens = enc.encode(text);
  if (tokens.length <= keep * 2) return text;
  const head = enc.decode(tokens.slice(0, keep));
  const tail = enc.decode(tokens.slice(-keep));
  const dropped = tokens.length - keep * 2;
  return `${new TextDecoder().decode(head)}\n\n[…${dropped} tokens omitted…]\n\n${new TextDecoder().decode(tail)}`;
}
