// [LAW:single-enforcer] One tokenizer instance for the entire app.
// [LAW:dataflow-not-control-flow] Per-kind correction dispatches on the `kind`
// tag in the input, not branches scattered across callers. The adapter emits
// BillableChunk[]; this module sums them using per-kind factors loaded from
// tokenizer-corrections.json (regenerated by scripts/analyze-calibration.ts).
//
// Raw estimator: chars / KIND_CHAR_DIVISORS[kind]. Tiktoken's vocab is too far
// from Claude's to be a useful base signal — empirical pilot data (docs/
// tokenizer-calibration.md) showed 50-70% slope error vs count_tokens oracle.
// Chars-per-token density varies by kind (English text ≈ 3.0, code/JSON ≈ 2.5),
// but within a kind it's remarkably linear against Anthropic's real counts
// (R² > 0.99 observed). Calibration learns a final a*raw+b polish that fits
// when the raw signal is already within ~10%.
//
// tiktoken stays imported for truncateMiddle — it's the right tool for
// preserving token boundaries when trimming text, even if we no longer trust
// its per-message counts.
import { encoding_for_model } from "tiktoken";
import type { BillableChunk, ContentKind } from "../../shared/types";
import corrections from "./tokenizer-corrections.json";

const enc = encoding_for_model("gpt-4o");

// Characters per token by kind. Pilot-data slopes sit within ~±10% of 1.0
// with these divisors — see docs/tokenizer-calibration.md for the regression
// plots. thinking_signature is billed at 0 by count_tokens (prior-turn
// thinking is always stripped); the divisor is irrelevant for it.
const KIND_CHAR_DIVISORS: Record<ContentKind, number> = {
  user_text: 3.0,
  assistant_text: 2.5,
  system_text: 2.5,
  tool_use_input: 2.5,
  tool_result_string: 2.5,
  tool_result_array: 2.5,
  thinking_text: 2.5,
  thinking_signature: 1.0,
};

interface KindCorrection {
  a: number; // slope
  b: number; // intercept
  sampleCount: number;
  r2: number;
  rmse: number;
}

interface CorrectionsFile {
  __comment?: string;
  generatedAt: string;
  corpusHashes: string[];
  kinds: Record<ContentKind, KindCorrection>;
}

const TABLE = corrections as CorrectionsFile;

/** Pre-calibration raw estimate: chars / kind-specific divisor. */
export function countRawBase(text: string, kind: ContentKind): number {
  const divisor = KIND_CHAR_DIVISORS[kind] ?? 3.0;
  return Math.round(text.length / divisor);
}

/** Apply the per-kind correction learned from calibration. */
export function correctRaw(raw: number, kind: ContentKind): number {
  const c = TABLE.kinds[kind];
  if (!c) return raw;
  return Math.max(0, Math.round(c.a * raw + c.b));
}

/** Count tokens for a single string tagged by content kind. */
export function countTokensByKind(text: string, kind: ContentKind): number {
  return correctRaw(countRawBase(text, kind), kind);
}

/** Sum corrected token counts over a tagged-chunk array. */
export function sumChunks(chunks: BillableChunk[]): number {
  let total = 0;
  for (const chunk of chunks) total += countTokensByKind(chunk.text, chunk.kind);
  return total;
}

/**
 * Back-compat for callers that don't have a ContentKind handy yet.
 * Treats the text as `assistant_text` — the most common kind. Prefer
 * countTokensByKind / sumChunks for new code.
 */
export function countTokens(text: string): number {
  return countTokensByKind(text, "assistant_text");
}

/** Keep the first and last `keep` tokens, replace the middle with ellipsis. */
export function truncateMiddle(text: string, keep = 100): string {
  const tokens = enc.encode(text);
  if (tokens.length <= keep * 2) return text;
  const head = enc.decode(tokens.slice(0, keep));
  const tail = enc.decode(tokens.slice(-keep));
  const dropped = tokens.length - keep * 2;
  return `${new TextDecoder().decode(head)}\n\n[…${dropped} tokens omitted…]\n\n${new TextDecoder().decode(tail)}`;
}
