// Render a SchemaArtifact as human-readable markdown. Pure function of its input
// (no IO, no time) so the output is fully deterministic given a stable schema.

import type {
  FieldSchema,
  RecordSchema,
  ReferenceEdge,
  Invariant,
  SchemaArtifact,
} from "./types";

const GEN_HEADER =
  "<!-- GENERATED by scripts/schema/run.ts — do not hand-edit. Re-run `npm run schema:extract` to regenerate. -->";

export function emitMarkdown(schema: SchemaArtifact): string {
  const parts: string[] = [];
  parts.push(GEN_HEADER);
  parts.push("");
  parts.push(`# ${titleCase(schema.corpusMeta.provider)} session format`);
  parts.push("");
  parts.push(emitCorpusMeta(schema));
  parts.push("");
  parts.push("## Record kinds");
  parts.push("");
  for (const kind of Object.keys(schema.records).sort()) {
    parts.push(emitRecord(kind, schema.records[kind], 3));
  }
  parts.push("## Reference edges (declared, verified)");
  parts.push("");
  parts.push(
    "Structural relationships the extractor verified against the corpus. A high orphan rate indicates a broken or outdated contract.",
  );
  parts.push("");
  parts.push(emitReferenceTable(schema.references));
  parts.push("");
  if (schema.suggestedReferences.length > 0) {
    parts.push("## Suggested references (unverified — human review required)");
    parts.push("");
    parts.push(
      "Field pairs with ≥95% value overlap that are not in the declared list. Review each: genuine relationship, coincidence, or a sign of misuse.",
    );
    parts.push("");
    parts.push(emitReferenceTable(schema.suggestedReferences));
    parts.push("");
  }
  parts.push("## API contracts (not corpus-derived)");
  parts.push("");
  parts.push(
    "These statements describe API-level invariants the file format depends on. The extractor cannot prove them — it only counts corpus violations. Zero observed violations is not a proof.",
  );
  parts.push("");
  for (const inv of schema.invariants) parts.push(emitInvariant(inv));
  return parts.join("\n");
}

function titleCase(s: string): string {
  return s.length === 0 ? s : s[0].toUpperCase() + s.slice(1);
}

function emitCorpusMeta(schema: SchemaArtifact): string {
  const m = schema.corpusMeta;
  return [
    "## Corpus",
    "",
    `- **Provider:** ${m.provider}`,
    `- **Root:** \`${m.corpusRoot}\``,
    `- **Files scanned:** ${m.filesScanned.toLocaleString()}`,
    `- **Records scanned:** ${m.recordsScanned.toLocaleString()}`,
    `- **Parse errors:** ${m.parseErrors.toLocaleString()}`,
    `- **Extractor version:** ${m.extractorVersion}`,
  ].join("\n");
}

function emitRecord(kind: string, rec: RecordSchema, headingLevel: number): string {
  const h = "#".repeat(headingLevel);
  const parts: string[] = [];
  parts.push(`${h} ${kind}`);
  parts.push("");
  parts.push(`**Observations:** ${rec.totalCount.toLocaleString()}`);
  parts.push("");
  if (rec.discriminator && rec.variants) {
    parts.push(`**Discriminated by:** \`${rec.discriminator}\``);
    parts.push("");
    const variantNames = Object.keys(rec.variants).sort();
    for (const v of variantNames) {
      parts.push(emitRecord(`${kind} (${rec.discriminator}=${JSON.stringify(v)})`, rec.variants[v], headingLevel + 1));
    }
  }
  if (rec.fields) {
    parts.push(emitFieldsTable(rec.fields, rec.totalCount));
    parts.push("");
    for (const fieldName of Object.keys(rec.fields).sort()) {
      const f = rec.fields[fieldName];
      if (f.arrayItem || f.nested) {
        parts.push(emitNestedField(fieldName, f, headingLevel + 1));
      }
    }
  }
  return parts.join("\n");
}

function emitFieldsTable(
  fields: Record<string, FieldSchema>,
  _parentCount: number,
): string {
  const header = "| Field | Kinds | Presence | Samples |";
  const sep = "|---|---|---|---|";
  const rows: string[] = [header, sep];
  for (const name of Object.keys(fields).sort()) {
    const f = fields[name];
    const presence = `${(f.presence * 100).toFixed(1)}%`;
    const kinds = f.valueKinds.join(", ");
    const samples = f.samples.map((s) => `\`${escapeMd(s)}\``).join(" · ") || "—";
    const enumStr = f.enum ? ` (enum: ${f.enum.map((e) => `\`${escapeMd(e)}\``).join(", ")})` : "";
    rows.push(`| \`${name}\` | ${kinds} | ${presence} | ${samples}${enumStr} |`);
  }
  return rows.join("\n");
}

function emitNestedField(
  name: string,
  f: FieldSchema,
  headingLevel: number,
): string {
  const h = "#".repeat(headingLevel);
  const parts: string[] = [];
  if (f.arrayItem) {
    parts.push(`${h} \`${name}[]\``);
    parts.push("");
    parts.push(emitRecord(`${name}[]`, f.arrayItem, headingLevel + 1));
  }
  if (f.nested) {
    parts.push(`${h} \`${name}\` (object)`);
    parts.push("");
    parts.push(emitRecord(name, f.nested, headingLevel + 1));
  }
  return parts.join("\n");
}

function emitReferenceTable(edges: ReferenceEdge[]): string {
  if (edges.length === 0) return "_None._";
  const header = "| From | To | Resolved / Total | Orphan rate |";
  const sep = "|---|---|---|---|";
  const rows = [header, sep];
  for (const e of edges) {
    rows.push(
      `| \`${e.from}\` | \`${e.to}\` | ${e.resolvedCount.toLocaleString()} / ${e.fromCount.toLocaleString()} | ${(e.orphanRate * 100).toFixed(2)}% |`,
    );
  }
  return rows.join("\n");
}

function emitInvariant(inv: Invariant): string {
  const parts: string[] = [];
  parts.push(`### ${inv.id}`);
  parts.push("");
  parts.push(inv.statement);
  parts.push("");
  if (inv.codeReferences.length > 0) {
    parts.push(`**Enforced at:** ${inv.codeReferences.map((r) => `\`${r}\``).join(", ")}`);
    parts.push("");
  }
  if (inv.observedViolations !== undefined) {
    parts.push(
      `**Observed violations:** ${inv.observedViolations.toLocaleString()} ` +
        (inv.observedViolations === 0
          ? "(no corpus record disproved this contract — not a proof of correctness)"
          : "— see samples below"),
    );
    parts.push("");
    if (inv.observedSamples && inv.observedSamples.length > 0) {
      parts.push("Violation samples:");
      parts.push("");
      for (const s of inv.observedSamples) parts.push(`- \`${escapeMd(s)}\``);
      parts.push("");
    }
  }
  return parts.join("\n");
}

function escapeMd(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/`/g, "\\`");
}
